src/MSSQLServerMonitoring.WebApp/Pages/Alerts/Alerts.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MSSQLServerMonitoring.Domain.AlertModel;
using MSSQLServerMonitoring.Infrastructure.Wrapper;

namespace MSSQLServerMonitoring.WebApp.Pages.Alerts
{
    public class AlertsModel : PageModel
    {
        private readonly IRepositoryWrapper _repositoryWrapper;
        public AlertsModel(IRepositoryWrapper repositoryWrapper)
        {
            _repositoryWrapper = repositoryWrapper;
        }
        [BindProperty(SupportsGet = true), DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        [BindProperty(SupportsGet = true), DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }
        [BindProperty(SupportsGet = true)]
        public List<Alert> Alerts { get; set; }
        public string IdSort { get; set; }
        public string DateSort { get; set; }

        public void OnGet()
        {
            Alerts = _repositoryWrapper.Alert.GetAll().Result;
        }

        public void OnGetGroupAlerts(string sortOrder)
        {
            List<Alert> alerts = _repositoryWrapper.Alert.GetAll().Result;

            DateSort = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            IEnumerable<Alert> alertsGroup = from ag in alerts
                                             select ag;

            switch (sortOrder)
            {
                case "date_desc":
                    alertsGroup = alertsGroup.OrderByDescending(ag => ag.TimeStamp);
                    break;
                default:
                    alertsGroup = alertsGroup.OrderBy(ag => ag.TimeStamp);
                    break;
            }

            Alerts = alertsGroup.ToList();
        }

        public void OnPost()
        {
            Alerts = _repositoryWrapper.Alert.GetOnCondition(a => (a.TimeStamp <= StartDate) && (a.TimeStamp >= EndDate)).Result;
        }
    }
}

src/MSSQLServerMonitoring.WebApp/Pages/Alerts/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MSSQLServerMonitoring.Domain.AlertModel;
using MSSQLServerMonitoring.Domain.QueryModel;
using MSSQLServerMonitoring.Infrastructure.Wrapper;
using System.Collections.Generic;
using System.Linq;

namespace MSSQLServerMonitoring.WebApp.Pages.Alerts
{
    public class DetailsModel : PageModel
    {
        private readonly IRepositoryWrapper _repositoryWrapper;
        public string textQuery { get; private set; }
        public string individualId { get; private set; }

        public DetailsModel(IRepositoryWrapper repositoryWrapper)
        {
            _repositoryWrapper = repositoryWrapper;
        }
        public IActionResult OnGet(int id)
        {
            //List<Alert> alerts = _repositoryWrapper.Alert.GetOnCondition(a => a.Id == id).Result;
            Alert alert = _repositoryWrapper.Alert.GetOnCondition(a => a.Id == id).Result.FirstOrDefault();

            if (alert == null)
            {
                return RedirectToPage("/NotFound");
            }

            individualId = alert.QueryId;

            if (alert.EventName == "rpc_completed")
            {
                textQuery = alert.Statement;
            }

            if (alert.EventName == "sql_statement_completed")
            {
                textQuery = alert.SqlText;
            }

            return Page();
        }
    }
}

src/MSSQLServerMonitoring.WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MSSQLServerMonitoring.WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/MSSQLServerMonitoring.WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MSSQLServerMonitoring.WebApp.Pages
{
    public class IndexModel : PageModel
    {
        public string Message { get; set; }
        public void OnGet()
        {
            Message = $"Welcome to our MS SQL Server Monitoring";
        }
    }
}

src/MSSQLServerMonitoring.WebApp/Pages/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MSSQLServerMonitoring.WebApp.Pages
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/MSSQLServerMonitoring.WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MSSQLServerMonitoring.WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/MSSQLServerMonitoring.WebApp/Pages/Alerts/Alerts.cshtml
@page 
@model MSSQLServerMonitoring.WebApp.Pages.Alerts.AlertsModel
@{
    ViewData["Title"] = "List alerts";
}
<h2>@ViewData["Title"]</h2>


<form method="post">
    Start Date : <input class="form-control col-3"
                        type="datetime-local"
                        data-val="true"
                        asp-for="StartDate"
                        value="2021-01-23T06:42:55.806">
    End Date : <input class="form-control col-3"
                        type="datetime-local"
                        data-val="true"
                        asp-for="EndDate"
                        value="2021-01-23T06:42:55.806">

    <input type="submit" value="Submit" class="btn btn-success mt-3" />
    <a asp-page="./Alerts" class="btn btn-link mt-3">Get All alerts</a>
    <div class="text-center">
        <table class="table mt-3">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Alerts[0].Id)
                    </th>
                    <th>
                        <a asp-page-handler="GroupAlerts" asp-route-sortOrder="@Model.DateSort">
                            @Html.DisplayNameFor(model => model.Alerts[0].TimeStamp)
                        </a>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Alerts[0].QueryId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Alerts[0].LogicalReads)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Alerts[0].Writes)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Alerts[0].Duration)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Alerts[0].Message)
                    </th>
                    <th>
                        Details
                    </th>           
                </tr>
            </thead>
            <tbody>
           @foreach (var item in Model.Alerts)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeStamp)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QueryId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LogicalReads)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Writes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                    <td>
                        <a asp-page="/Alerts/Details" asp-route-Id="@item.Id" class="btn m-1 btn-outline-info">View</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    
</form>





@*<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Date</th>
            <th>Query-id</th>
            <th>Message</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Alerts)
        {
        <tr>
            <td>@item.Id</td>
            <td>@item.TimeStamp</td>
            <td>@item.AttachActivityId</td>
            <td>@item.Message</td>
            <td>@item.Status</td>
        </tr>
        }
    </tbody>
</table>*@

src/MSSQLServerMonitoring.WebApp/Pages/Alerts/Details.cshtml
@page "{id}"
@model MSSQLServerMonitoring.WebApp.Pages.Alerts.DetailsModel
@{
    ViewData["Title"] = "Details";
}
<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="text-left col-12">
        <h4>Individual request ID: @Model.individualId</h4><hr/>
    </div>
    <div class="text-left col-12">
        <h4>SQL - text:</h4>
        <p>
            @Model.textQuery
        </p>
    </div>
    <div class="text-center col-12">
        <a asp-page="Alerts" class="btn btn-success">Back</a>
    </div>
</div>

src/MSSQLServerMonitoring.WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">@Model.Message</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/MSSQLServerMonitoring.WebApp/Pages/NotFound.cshtml
@page
@model MSSQLServerMonitoring.WebApp.Pages.NotFoundModel
@{
    ViewData["Title"] = "Not Found";
}

<div class="row">
    <div class="col text-center">
        <img src="~/images/NotFound.png" alt="Page Not Found" />
    </div>
</div>

<div class="row">
    <div class="col text-center">
        <h1>The resource you are looking for cannot be found!</h1>
        <a asp-page="/Alerts/Alerts" class="btn btn-primary">Click here to get back to Alerts list page</a>
    </div>
</div>

src/MSSQLServerMonitoring.WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MSSQLServerMonitoring</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MSSQLServerMonitoring</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Alerts/Alerts">Alerts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MSSQLServerMonitoring - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>